"""password added

Revision ID: 275cf09f7937
Revises: f0e3b3193fb0
Create Date: 2019-02-25 15:46:50.267337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275cf09f7937'
down_revision = 'f0e3b3193fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'pass_secure')
    op.drop_column('users', 'password')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
